network:
  version: 2
  renderer: networkd

  ethernets:
    end0:
      dhcp4: true

  wifis:
    wlan0:
      dhcp4: false
      addresses:
        - 172.31.106.2/24
      access-points:
        "HARELab-RTK-Bucket":
          mode: ap
          password: "password"
